name: Update Frida Version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_frida:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Update Frida Version
        run: ./update_frida_version.sh
      
      - name: Read version information
        id: version_info
        run: |
          if [ -f .frida_old_version ] && [ -f .frida_new_version ] && [ -f .frida_version_changed ]; then
            OLD_VERSION=$(cat .frida_old_version)
            NEW_VERSION=$(cat .frida_new_version)
            VERSION_CHANGED=$(cat .frida_version_changed)
            
            echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "version_changed=$VERSION_CHANGED" >> $GITHUB_OUTPUT
            
            rm -f .frida_old_version .frida_new_version .frida_version_changed
          else
            echo "Error: Version information files not found"
            exit 1
          fi
      
      - name: Create Pull Request
        if: steps.version_info.outputs.version_changed == 'true'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: "Update Frida version from ${{ steps.version_info.outputs.old_version }} to ${{ steps.version_info.outputs.new_version }}"
          title: "Update Frida version to ${{ steps.version_info.outputs.new_version }}"
          body: |
            This PR updates the Frida version in the Makefile from `${{ steps.version_info.outputs.old_version }}` to `${{ steps.version_info.outputs.new_version }}`.
            
            **Changes:**
            - 🎉 Updated `FRIDA_VERSION` from `${{ steps.version_info.outputs.old_version }}` to `${{ steps.version_info.outputs.new_version }}`
            
            **Release Information:**
            - 📋 [Frida Release Notes](https://github.com/frida/frida/releases/tag/${{ steps.version_info.outputs.new_version }})
            - 📰 [Frida News](https://frida.re/news/)
            
            This update was automatically generated by the scheduled workflow.
          branch: update-frida-version-${{ steps.version_info.outputs.new_version }}
          delete-branch: true